### ISSUE TITLE
pass IPN-Message to callback functions

### ISSUE THREAD

**Issue by Dormilich** [mike182uk/paypal-ipn-listener#12]
Hi,

I think it would be a reasonable idea to pass either the IPN Message or the Listener instance to the callback functions (when they’re executed off the stack) so that you don’t have to import them explicitly every time (since there is often data in the IPN message that are required for further processing).

Dormilich

**Comment by mike182uk** [comment]
Howdy, i have just released a new version of the library that uses symfony's event dispatcher to handle the callback stack. This means an event object is now passed to the callable, and the original IPN message can be retrieved from the event using the `getMessage` method.
