### ISSUE TITLE
allow callables to be passed to the Listener

### ISSUE THREAD

**Issue by Dormilich** [mike182uk/paypal-ipn-listener#13]
Hi,

it would add a great deal of flexibility if callables and not only anonymous functions would be allowed in the callback stack.

Dormilich

**Comment by Dormilich** [comment]
As of PHP 5.4 you could use the `callable` type hint.

**Comment by mike182uk** [comment]
Howdy, i have just released a new version of the library that uses symfony's event dispatcher to handle the callback stack. This means callables can now be used :)
