### ISSUE TITLE
Using the ArrayListenerBuilder always returns Invalid

### ISSUE THREAD

**Issue by chrisjohnstone** [mike182uk/paypal-ipn-listener#16]
Hi Mike, thanks for the latest version of your listener.

I've been able to get the listener working with the `InputStreamListenerBuilder` and it returns a nice string of data from paypal. When I substitute in the `ArrayListenerBuilder` and log the `$ipnMessage` however, I always get an Invalid response from Paypal.

Would a verified response return an array as part of the message?

**Comment by mike182uk** [comment]
Hey Chris,

Can you share an example of what your code looks like so i can take a look?

**Comment by chrisjohnstone** [comment]
Sure, I'm using Laravel 4.2. My `IPNController` looks like this:

    use Mdb\PayPal\Ipn\Event\MessageVerifiedEvent;
    use Mdb\PayPal\Ipn\Event\MessageInvalidEvent;
    use Mdb\PayPal\Ipn\Event\MessageVerificationFailureEvent;
    use Mdb\PayPal\Ipn\ListenerBuilder\Guzzle\ArrayListenerBuilder as ListenerBuilder;

and in the method:

    $listenerBuilder = new ListenerBuilder();
    $listenerBuilder->useSandbox();
    $listener = $listenerBuilder->build();

    $listener->onInvalid(function (MessageInvalidEvent $event) {
        $ipnMessage = $event->getMessage();
			Log::info("INVALID\n\n" . $ipnMessage);
		});
		$listener->onVerified(function (MessageVerifiedEvent $event) {
			$ipnMessage = $event->getMessage();
			Log::info("VERIFIED\n\n" . $ipnMessage);
		});
		$listener->onVerificationFailure(function (MessageVerificationFailureEvent $event) {
			$error = $event->getError();
			Log::info("VERIFICATION FAILURE\n\n" . $error);
    });
    $listener->listen();

My Log file looks like this:

    [2015-04-28 12:21:10] production.INFO: INVALID

    [] []

Also, a small point: I think there's a typo in the README.md under the Sandbox mode section.

`$listnerBuilder->useSandbox(); // use PayPal sandbox` I think is supposed to read `$listenerBuilder...`

**Comment by mike182uk** [comment]
Thanks, i'll fix the readme typo.

As for your problem, you need to manually give the array listener builder your data as it is not automatically getting it from the input stream. So you would need something like:

```php
$data = array(
    'foo' => Post::get('foo'),
    'bar' => Post::get('bar'),
);

$listenerBuilder = new ListenerBuilder();

$listenerBuilder->setData($data); // set the data to use to create the message
$listenerBuilder->useSandbox();

$listener = $listenerBuilder->build();

$listener->onInvalid(function (MessageInvalidEvent $event) {
    $ipnMessage = $event->getMessage();
    
    Log::info("INVALID\n\n" . $ipnMessage);
});

$listener->listen();
```

**Comment by chrisjohnstone** [comment]
Thanks, Mike. Got it working smoothly now with:

    public $data;

	public function listener()
	{
		$this->data = Input::all();

		$listenerBuilder = new ListenerBuilder();

		$listenerBuilder->setData($this->data); // set the data to use to create the message
		$listenerBuilder->useSandbox();

		$listener = $listenerBuilder->build();

		$listener->onInvalid(function (MessageInvalidEvent $event) {
			$ipnMessage = $event->getMessage();
			Log::info("INVALID\n\n" . $ipnMessage);
		});
		$listener->onVerified(function (MessageVerifiedEvent $event) {
			$ipnMessage = $event->getMessage();
			Log::info("VERIFIED\n\n" . $ipnMessage);

			$this->store($this->data); // Call the store method to save the data to the DB

		});
		$listener->onVerificationFailure(function (MessageVerificationFailureEvent $event) {
			$error = $event->getError();
			Log::info("VERIFICATION FAILURE\n\n" . $error);
		});

		$listener->listen();

	}

    // ... go on to store data...

**Comment by mike182uk** [comment]
Cool, glad you got it sorted. I'll add a few more examples to cover this. Also on a side note, you can also pass callables to the listener events which might make your code abit cleaner:

```php
class PayPalProcessor
{
    public function initListener()
    {
        $listenerBuilder = new ListenerBuilder();

        $listenerBuilder->setData(
            $this->getInput()
        );

        $listenerBuilder->useSandbox();

        $listener = $listenerBuilder->build();

        $listener->onVerified(array($this, 'onVerified'));

        $listener->listen();
    }

    /**
     * @param MessageVerifiedEvent $event
     */
    public function onVerified(MessageVerifiedEvent $event)
    {
        $data = $event->getMessage()->getAll();

        $this->store(data);
    }

    /**
     * @return array
     */
    public function getInput()
    {
        return Input::all();
    }
}
````

**Comment by chrisjohnstone** [comment]
Nice, that's really useful and tidy. I'll implement that in my class. I think your examples are great and all I needed was a better understanding of the IPN system in that it was POSTing data to the listener URL. The array data was always available, I just didn't realise.
