### ISSUE TITLE
Question: Is there a way to get a textRerport()?

### ISSUE THREAD

**Issue by fenixkim** [mike182uk/paypal-ipn-listener#19]
First to all, thanks for this great repo.

I'm very sorry to ask this question, but is there any way to get a report similar to https://github.com/Quixotix/PHP-PayPal-IPN#example-report?

**Comment by mike182uk** [comment]
Hey,

Unfortunately not, although i could see why this maybe useful. 

Alternatively you have access to the contents of the IPN message inside the callback:

```
$listener->onInvalid(function (MessageInvalidEvent $event) {
   $ipnMessage = $event->getMessage();

   // generate report here...
});
```

so you could manually generate a report yourself, although you would not have access to the HTTP request / body data.
