### ISSUE TITLE
Can't install with composer (dependency problem)

### ISSUE THREAD

**Issue by dejan7** [mike182uk/paypal-ipn-listener#20]
Composer output:

    Problem 1
    - Installation request for mike182uk/paypal-ipn-listener ~4.0 -> satisfiable by mike182uk/paypal-ipn-listener[v4.0.0].
    - mike182uk/paypal-ipn-listener v4.0.0 requires guzzlehttp/guzzle ~5.2 -> no matching package found.

If you are still maintaining this package you should update guzzle req. and change the potential guzzle usage. Thanks

**Comment by mike182uk** [comment]
Hi,

With this `composer.json`:

```json
{
    "require": {
        "mike182uk/paypal-ipn-listener": "~4.0"
    }
}
```

i get this result:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/event-dispatcher (v2.8.0)
    Downloading: 100%

  - Installing react/promise (v2.2.1)
    Loading from cache

  - Installing guzzlehttp/streams (3.0.0)
    Loading from cache

  - Installing guzzlehttp/ringphp (1.1.0)
    Loading from cache

  - Installing guzzlehttp/guzzle (5.3.0)
    Loading from cache

  - Installing mike182uk/paypal-ipn-listener (v4.0.0)
    Downloading: 100%

symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/event-dispatcher suggests installing symfony/http-kernel ()
Writing lock file
Generating autoload files
```

Im not entirely sure why you would be seeing that error, are you using packagist as your package repository or do you have custom package repositories setup?

**Comment by mike182uk** [comment]
@dejan7 Did you manage to resolve this issue?

**Comment by mike182uk** [comment]
I'm going to close this for now as i haven't heard anything back. Feel free to re-open if your still having the above problem.
