### ISSUE TITLE
Guzzle 6

### ISSUE THREAD

**Issue by jeremykendall** [mike182uk/paypal-ipn-listener#21]
Any plans for a Guzzle 6.x version? Thanks!

**Comment by mike182uk** [comment]
It wasn't something i had plans on yet. Is the older version of guzzle causing problems for you?

**Comment by jeremykendall** [comment]
The older version is fine, we just have a dependency conflict because the [Neoxygen NeoClient](https://github.com/neoxygen/neo4j-neoclient) requires Guzzle `^6.0`.

Please don't refactor on my account. I was looking for options to rolling my own and found your lib. It looks amazing, but since I couldn't use it I settled for PayPal's `PPIPNMessage`, using it pretty much like [this example](https://github.com/paypal/adaptivepayments-sdk-php/blob/namespace-php5.3/samples/IPN/IPNListener.php).

**Comment by mike182uk** [comment]
Ah thats a shame.

We could look at upgrading it and tagging a new version that plays nicely? 

Guzzle 6 depends on `5.5` and this library supports `5.4`. `5.4` is end of life now anyways so i have no issues with this dep being upgraded and the library being bumped to only support `5.5` (if somebody needs it for `5.4`, they can just pin an older version).

**Comment by jeremykendall** [comment]
> We could look at upgrading it and tagging a new version that plays nicely?

That would be great. I'd be happy to volunteer, but I can't commit to a timeline :frowning: It would probably be a while because startup, toddler, moving, blah, blah, blah.

> i have no issues with this dep being upgraded and the library being bumped to only support 5.5

Awesome!

**Comment by Lctrs** [comment]
I would recommend to use [HTTPlug](http://docs.php-http.org/en/latest/) instead. This will let users chose whatever they want to use (Guzzle 5, 6, Curl, etc.)

**Comment by mike182uk** [comment]
@jeremykendall You have probably found some other solution now, but the latest tagged version now uses the latest version of guzzle.
