### ISSUE TITLE
How to pull individual IPN fields..??

### ISSUE THREAD

**Issue by angelleye** [mike182uk/paypal-ipn-listener#22]
I see in your examples that $event->getMessage() returns the raw IPN string.  Is there any way to pull individual fields or is it left up to me to parse that string at that point?

**Comment by mike182uk** [comment]
The [message object](https://github.com/mike182uk/paypal-ipn-listener/blob/master/src/Message.php) is returned from this call. The `get` method should return a specific field, or you can use `getAll` to get an array of all fields:

```php
$field = $message->get('<field>');

// or 

$data = $message->getAll();

```

**Comment by angelleye** [comment]
Thanks!!
