### ISSUE TITLE
Listener is bound to EventDispatcher

### ISSUE THREAD

**Issue by mablae** [mike182uk/paypal-ipn-listener#25]
This typehint should be the `EventDispatcherInterface` instead: 

https://github.com/mike182uk/paypal-ipn-listener/blob/master/src/Listener.php#L40

refs #24

**Comment by mike182uk** [comment]
Fixed in https://github.com/mike182uk/paypal-ipn-listener/commit/b49fe191b69f0226056d36e6938bbb76bda87b28
