### ISSUE TITLE
IPN verification failure

### ISSUE THREAD

**Issue by mike182uk** [mike182uk/paypal-ipn-listener#30]
A few people have reported they are having problems with the IPN messages not being verified when they should be, most notably here: https://github.com/mike182uk/paypal-ipn-listener/issues/28

We need to do some investigation to see what is actually going on here to try and resolve the problem.

**Comment by mike182uk** [comment]
@sebdesign I have opened a new issue to try resolve the problem you have reported in #28.

To help debug, can you add a comment here showing what you received from PayPal and what you sent back to PayPal? You might have to hack a `var_dump` somewhere. 

This will help me narrow down the problem.

**Comment by sebdesign** [comment]
Hi @mike182uk , I will try to find some time tomorrow to show you exactly what I have received from Paypal.

**Comment by Bulmer** [comment]
Just wondering if this has been fixed yet? I dont mind sending you some data dumps if it would help sort this out. I'm just about to launch my upgraded website and i'm not sure if this error is going to carry over when live. I've never had trouble before with your Listener, however i'm now using php7.0 if that helps pinpoint whats going on..

**Comment by mike182uk** [comment]
Hey @Bulmer

Are you experiencing this problem? If so then feel free to add some data dumps to this thread to help with debugging.

If you have not experienced the problem mentioned here before, then i would imagine things should still work fine with PHP 7. If this is not the case and you are seeing things not working, then any debugging info you can add to this thread would be a great help.

**Comment by sebdesign** [comment]
Hi @mike182uk and @Bulmer ,

I'm still having problems after migrating to a new server (CentOS 7, PHP 7). I will try to provide some data dumps in the following days.

**Comment by mike182uk** [comment]
😔 Anything you can provide should be able help us debug this further.

Would be interesting to see if @Bulmer experiences the problem when upgrading to PHP7.

**Comment by Bulmer** [comment]
Hey @mike182uk and Sebastien. I can only help with PHP7.0, because i've already upgraded. I must also add that i'm still running a dev setup, using paypal sandbox and allowing ipns to come back to me through an open port in my router. There should be no problems with this though, as i've been doing this for a few years now with no problems.
This is the data sent back to me through MessageInvalidEvent->getMessage().
`mc_gross=103.00&invoice=5976&protection_eligibility=Ineligible&payer_id=MZZZ795SQJMUE&tax=0.00&payment_date=05%3A13%3A38%2BApr%2B13%2C%2B2017%2BPDT&payment_status=Completed&charset=windows-1252&first_name=joe&mc_fee=2.77&notify_version=3.8&custom=&payer_status=unverified&business=seller%40foo.com.au&quantity=1&verify_sign=ZZ3Bnd85qDAG2ivRgEH-F3bq0tH3A79StyleVwouOdtodtFni4UvszbK&txn_id=9DW777711E214470K&payment_type=instant&last_name=blow&receiver_email=seller%40foo.com.au&payment_fee=&receiver_id=XM7ZZATM79PPS&txn_type=pro_api&item_name=&mc_currency=AUD&item_number=&residence_country=AU&test_ipn=1&receipt_id=3496-3599-5070-7302&handling_amount=0.00&transaction_subject=&payment_gross=&shipping=0.00&ipn_track_id=5b1ss5e58cca5`
Running this string through both rawurldecode and urldecode returns this, for payment_date, which may? be the problem?
`payment_date=05:13:38+Apr+13,+2017+PDT`

**Comment by mike182uk** [comment]
Hey @Bulmer, thanks for this.

Just to be clear, can you confirm if you are experiencing this problem? If so does it happen in the sandbox AND live or just one of those? 

Could you also provide the data that you initially receive from PayPal so we can see the difference between the original you received, to the data that is being sent to PayPal to verify? You should be able to get this by executing `echo file_get_contents('php://input');` before the listener is setup.

**Comment by Bulmer** [comment]
I can only confirm it happens in the sandbox as i'm not live with this website yet. Also its a Business-Pro account and i'm using self-signed certs on this dev setup, but only sending to http.
Heres the data:
initial data (file_get_contents('php://input')):
`mc_gross=25.00&invoice=GIFT32&protection_eligibility=Ineligible&payer_id=MZFP795SQJMUE&tax=0.00&payment_date=01%3A33%3A47+Apr+18%2C+2017+PDT&payment_status=Completed&charset=UTF-8&first_name=joe&mc_fee=0.90&notify_version=3.8&custom=&payer_status=unverified&business=seller%40foo.com.au&quantity=1&verify_sign=A0FIHGGYIJ-nD8w6ijMHucFJMWkkADT5qZp6V-EP7NY.4dsb5vztmqv6&txn_id=3A569269YP888351D&payment_type=instant&last_name=blow&receiver_email=seller%40foo.com.au&payment_fee=&receiver_id=XM7UYATM79PPS&txn_type=pro_api&item_name=&mc_currency=AUD&item_number=&residence_country=AU&test_ipn=1&receipt_id=2564-5408-1478-7916&handling_amount=0.00&transaction_subject=&payment_gross=&shipping=0.00&ipn_track_id=3751c2dc7be22`

Data through MessageInvalidEvent->getMessage():
`mc_gross=25.00&invoice=GIFT32&protection_eligibility=Ineligible&payer_id=MZFP795SQJMUE&tax=0.00&payment_date=01%3A33%3A47%2BApr%2B18%2C%2B2017%2BPDT&payment_status=Completed&charset=UTF-8&first_name=joe&mc_fee=0.90&notify_version=3.8&custom=&payer_status=unverified&business=seller%40foo.com.au&quantity=1&verify_sign=A0FIHGGYIJ-nD8w6ijMHucFJMWkkADT5qZp6V-EP7NY.4dsb5vztmqv6&txn_id=3A569269YP888351D&payment_type=instant&last_name=blow&receiver_email=seller%40foo.com.au&payment_fee=&receiver_id=XM7UYATM79PPS&txn_type=pro_api&item_name=&mc_currency=AUD&item_number=&residence_country=AU&test_ipn=1&receipt_id=2564-5408-1478-7916&handling_amount=0.00&transaction_subject=&payment_gross=&shipping=0.00&ipn_track_id=3751c2dc7be22`

**Comment by mike182uk** [comment]
Thanks @Bulmer,

Are you using the IPN simulator to test this or are you putting through a real order?

For some reason the spaces in the `payment_date` you have received are not encoded the way we are expecting - they are encoded using a `+` instead of a `%20`. So when the date you are provided gets decoded using `rawurldecode` it is `01:33:47+Apr+18,+2017+PDT` (`+` not converted to space). When this gets re-encoded to be sent back to PayPal for verification `rawurlencode` is encoding it to `01%3A33%3A47%2BApr%2B18%2C%2B2017%2BPDT` which is obviously not the same as what Paypal sent in the first place.

I've just done a test with the IPN simulator, and the date i'm getting sent to me is encoded as i would expect: `Tue%20Apr%2018%202017%2009%3A44%3A03%20GMT%2B0100%20%28BST%29` (which decodes to `Tue Apr 18 2017 09:44:03 GMT+0100 (BST)`). 

So i guess we need to find out why the date being sent to you is not encoded how we would expect, and why you are receiving a different encoded date to what i am.

**Comment by Bulmer** [comment]
Im not using the IPN simulator. I've got a Local Dev setup of my upgraded
ecommerce site which runs on the latest Laravel PHP framework. Im now
running PHP7.1, but 7.0 was acting the same anyway.

**Comment by mike182uk** [comment]
Hey @Bulmer,

Sorry to be a pain, but i don't suppose you could dump the data your sending to PayPal from your HTML form here, then details of the full HTTP request your getting posted to the listener (i.e http headers, raw body etc.)

Could you also give try testing the IPN simulator against your implementation to see if you get the same result?

**Comment by Bulmer** [comment]
Hey @mike182uk . Yes I can do that today. How would you like me to capture the HTTP request data? Also is it possible to pm this info, to save me going through it all and editing it? No, I can't use the Simulator as i'm using a specific port to post the IPN to and it doesn't allow that. (although the sandbox doesnt mind..). Cheers.

**Comment by mike182uk** [comment]
Hey @Bulmer,

Could you try using https://requestb.in/ as the IPN URL for your form, this should capture the all of the data that is being posted to you. You should be able to share the URL here once PayPal has made a request to it.

Im trying to work out why the `payment_date` for you is not encoded how we are expecting. When i am testing with the PayPal IPN simulator, the spaces are being encoded correctly (`%20` instead of `+`)

Also as a test, when you provide an email address can you use one with a `+` in it i.e `foo+bar@example.com` so we can see what PayPal does with the `+` in that email address. Also if you could add a couple of spaces into another field, the custom field or something (i.e `foo bar baz`) that would be great.

**Comment by Bulmer** [comment]
This has thrown a spanner in the works @mike182uk . I thought i'd give the standard paypal ipn code for php a try from Github: https://github.com/paypal/ipn-code-samples/tree/master/php and it worked without any validation problems!

**Comment by mike182uk** [comment]
@Bulmer Did you get chance to capture the request using https://requestb.in/? Im not going to be able to debug much further without knowing how/what data is being sent to you (before it hits your web server)

**Comment by Bulmer** [comment]
Hey @mike182uk . My email is temporarily available in my profile. Email me and i'll send you the link.

**Comment by sebdesign** [comment]
Hey @mike182uk ,

I finally found the time to do some tests on my end.
I have a staging server set up, and both merchant and buyer sandbox accounts.

I made a payment on the staging app, which sent an IPN to my end.
When I log in into the merchant sandbox account, I can see the message in the IPN history.

These are the details on the page:

```
Message ID: 61A03328NT6281116
Date/time created: 6/1/2017 11:25 PDT
Original/Resent: Original
Latest delivery attempt date/time: 6/1/2017 11:25 PDT
Notification URL: https://dev.admin.contraversus.com/paypal/ipn
HTTP response code What's this?: 200
Delivery status: Sent
No. of retries: 0
Transaction ID: 63V18898CL584435M
IPN type: Transaction made
```

And this is the payload:

```
mc_gross=29.90&protection_eligibility=Eligible&address_status=confirmed&item_number1=&payer_id=A9U7X8B6NU6QQ&address_street=1 Main St&payment_date=11:25:37 Jun 01, 2017 PDT&payment_status=Completed&charset=windows-1252&address_zip=95131&first_name=Sebastien&mc_fee=1.22&address_country_code=US&address_name=Sebastien Nikolaou&notify_version=3.8&custom=37893&payer_status=verified&business=merchant@contraversus.com&address_country=United States&num_cart_items=1&address_city=San Jose&verify_sign=A8vyPPy7mObxAPq5psJu6mY0fl34AHDrxUuL.IQuzfE-5wDxS.ySH1yp&payer_email=buyer@contraversus.com&txn_id=63V18898CL584435M&payment_type=instant&last_name=Nikolaou&item_name1= 10ml&address_state=CA&receiver_email=merchant@contraversus.com&payment_fee=&shipping_discount=0.00&quantity1=1&insurance_amount=0.00&receiver_id=DTZ7AV9BXXWLQ&txn_type=cart&discount=10.00&mc_gross_1=39.90&mc_currency=EUR&residence_country=US&test_ipn=1&shipping_method=Default&transaction_subject=&payment_gross=&ipn_track_id=7569c564c9a08
```

On my end, this is the incoming request:

```
[2017-06-01 21:25:51] dev.DEBUG: mc_gross=29.90&protection_eligibility=Eligible&address_status=confirmed&item_number1=&payer_id=A9U7X8B6NU6QQ&address_street=1+Main+St&payment_date=11%3A25%3A37+Jun+01%2C+2017+PDT&payment_status=Completed&charset=windows-1252&address_zip=95131&first_name=Sebastien&mc_fee=1.22&address_country_code=US&address_name=Sebastien+Nikolaou&notify_version=3.8&custom=37893&payer_status=verified&business=merchant%40contraversus.com&address_country=United+States&num_cart_items=1&address_city=San+Jose&verify_sign=A8vyPPy7mObxAPq5psJu6mY0fl34AHDrxUuL.IQuzfE-5wDxS.ySH1yp&payer_email=buyer%40contraversus.com&txn_id=63V18898CL584435M&payment_type=instant&last_name=Nikolaou&item_name1=%1A%1A%1A%1A%1A%1A%1A%1A%1A+10ml&address_state=CA&receiver_email=merchant%40contraversus.com&payment_fee=&shipping_discount=0.00&quantity1=1&insurance_amount=0.00&receiver_id=DTZ7AV9BXXWLQ&txn_type=cart&discount=10.00&mc_gross_1=39.90&mc_currency=EUR&residence_country=US&test_ipn=1&shipping_method=Default&transaction_subject=&payment_gross=&ipn_track_id=7569c564c9a08
```

On my logs the IPN is marked as invalid. Here is the array dump from the `MessageInvalidEvent`:
```
2017-06-01 21:25:52] dev.ERROR: array (
  'mc_gross' => '29.90',
  'protection_eligibility' => 'Eligible',
  'address_status' => 'confirmed',
  'item_number1' => '',
  'payer_id' => 'A9U7X8B6NU6QQ',
  'address_street' => '1+Main+St',
  'payment_date' => '11:25:37+Jun+01,+2017+PDT',
  'payment_status' => 'Completed',
  'charset' => 'windows-1252',
  'address_zip' => '95131',
  'first_name' => 'Sebastien',
  'mc_fee' => '1.22',
  'address_country_code' => 'US',
  'address_name' => 'Sebastien+Nikolaou',
  'notify_version' => '3.8',
  'custom' => '37893',
  'payer_status' => 'verified',
  'business' => 'merchant@contraversus.com',
  'address_country' => 'United+States',
  'num_cart_items' => '1',
  'address_city' => 'San+Jose',
  'verify_sign' => 'A8vyPPy7mObxAPq5psJu6mY0fl34AHDrxUuL.IQuzfE-5wDxS.ySH1yp',
  'payer_email' => 'buyer@contraversus.com',
  'txn_id' => '63V18898CL584435M',
  'payment_type' => 'instant',
  'last_name' => 'Nikolaou',
  'item_name1' => '+10ml',
  'address_state' => 'CA',
  'receiver_email' => 'merchant@contraversus.com',
  'payment_fee' => '',
  'shipping_discount' => '0.00',
  'quantity1' => '1',
  'insurance_amount' => '0.00',
  'receiver_id' => 'DTZ7AV9BXXWLQ',
  'txn_type' => 'cart',
  'discount' => '10.00',
  'mc_gross_1' => '39.90',
  'mc_currency' => 'EUR',
  'residence_country' => 'US',
  'test_ipn' => '1',
  'shipping_method' => 'Default',
  'transaction_subject' => '',
  'payment_gross' => '',
  'ipn_track_id' => '7569c564c9a08',
)
```

**Comment by Swader** [comment]
On a somewhat related note, here's some additional news: when using the sandbox URL (updated URL in PRs #31), the code needs to be using `urlencode` and `urldecode`. When using the live URL, the code needs to be using `rawurlencode` and `rawurldecode`. I'll make a new PR for this as soon as #31 is merged. Ping @mablae @mike182uk

**Comment by Swader** [comment]
I've made a SandboxAware version of the IPN listener package, visible [here](https://github.com/Swader/paypal-ipn-listener/tree/patch-sandboxaware). Testing with a live client right now and will report back on how it works. If you can verify this is happening across the board, then we've found a bug in Paypal's live vs simulated environment and the whole package should be changed to reflect this. If it's an isolated case, for whatever reason, then my sandboxaware branch can be merged in as a new feature - I've tested it quite extensively and it seems to be working fine.

**Comment by sebdesign** [comment]
Hi folks,

I updated to 8.0.1, and used the `ArrayListenerBuilder` instead of the `InputStreamListenerBuilder`  in my Laravel application. This way I can use the framework's request data in production and in my integration tests.

I confirm that it works in both live/sandbox (production/testing) environments!
Although my tests are using the sandbox mode that is always returning `INVALID`, I will test it in a staging environment.

Thank you @Swader !

**Comment by ggeorgiev96** [comment]
Just had the same issue with the package - all Live transactions were Invalid for successful payments, strangely enough when the code from the [PayPal IPN documentation]( https://developer.paypal.com/docs/classic/ipn/ht_ipn/ ) is used everything worked as expected, perhaps this could help you debug what is causing this behavior ?

**Comment by willemstuursma** [comment]
I think we found the problem: #32.

**Comment by seyfer** [comment]
@willemstuursma, thanks. 

@mike182uk, would be good to have `8.0.2` tag after it's merged for testing.

**Comment by mike182uk** [comment]
Thanks again @willemstuursma 

@seyfer I've published `v8.0.2` with the changes.

Im going to close this issue for now, but feel free to comment or re-open if your still having this problem.

**Comment by BarbzYHOOL** [comment]
just wanted to say that with or without rawurlencode, even if it sends a "+" or a "%20" it works fine now on production

However I still can't make it work in some cases (examples here: https://github.com/paypal/ipn-code-samples/issues/161 )

Another thing to note: the ipn simulator won't send the special characters in utf-8 cause it's a piece of shit of a software, so you have to test on sandbox mode

**Comment by rocfra** [comment]
Hello,

I'm testing Paypal listener using IPN simulator or sandbox business account. 
All verifications are "VERIFICATION FAILED".
But if I paste $req content in this GET url, it seems working.
Do you have an idea of what I could try to solve that ?
Thank you !

https://ipnpb.sandbox.paypal.com/cgi-bin/webscr?cmd=_notify-validate&payment_type=instant&payment_date=12%3A18%3A05+Jul+26%2C+2022+PDT&payment_status=Completed&payer_status=verified&first_name=John&last_name=Smith&payer_email=buyer%40paypalsandbox.com&payer_id=TESTBUYERID01&address_name=John+Smith&address_country=United+States&address_country_code=US&address_zip=95131&address_state=CA&address_city=San+Jose&address_street=123+any+street&business=seller%40paypalsandbox.com&receiver_email=seller%40paypalsandbox.com&receiver_id=seller%40paypalsandbox.com&residence_country=US&item_name1=something&item_number1=AK-1234&quantity=1&shipping=3.04&tax=2.02&mc_currency=USD&mc_fee=0.44&mc_gross=12.34&mc_gross_1=12.34&mc_handling=2.06&mc_handling1=1.67&mc_shipping=3.02&mc_shipping1=1.02&txn_type=cart&txn_id=899327589&notify_version=2.4&custom=xyz123&invoice=abc1234&test_ipn=1&verify_sign=Ak94TBBVVaEGZP89tcv-BEF1UbMXAgYLsoaSyPHTU7.g0xdYOqgpg7bg

**Comment by rocfra** [comment]
Hello, this url with $req content works for Paypal verification.
But Paypal IPN listener says "VERIFICATION FAILED".
What do you think I should do ?
Thank you !

`https://ipnpb.sandbox.paypal.com/cgi-bin/webscr?cmd=_notify-validate&payment_type=instant&payment_date=12%3A18%3A05+Jul+26%2C+2022+PDT&payment_status=Completed&payer_status=verified&first_name=John&last_name=Smith&payer_email=buyer%40paypalsandbox.com&payer_id=TESTBUYERID01&address_name=John+Smith&address_country=United+States&address_country_code=US&address_zip=95131&address_state=CA&address_city=San+Jose&address_street=123+any+street&business=seller%40paypalsandbox.com&receiver_email=seller%40paypalsandbox.com&receiver_id=seller%40paypalsandbox.com&residence_country=US&item_name1=something&item_number1=AK-1234&quantity=1&shipping=3.04&tax=2.02&mc_currency=USD&mc_fee=0.44&mc_gross=12.34&mc_gross_1=12.34&mc_handling=2.06&mc_handling1=1.67&mc_shipping=3.02&mc_shipping1=1.02&txn_type=cart&txn_id=899327589&notify_version=2.4&custom=xyz123&invoice=abc1234&test_ipn=1&verify_sign=Ak94TBBVVaEGZP89tcv-BEF1UbMXAgYLsoaSyPHTU7.g0xdYOqgpg7bg`

**Comment by rocfra** [comment]
I deleted all cURL process and I tried this code which works very well in my environment for the moment.
Result is "Completed Successfully" for all IPN wright.
What do you think of this solution ?

```
$url = $this->getPaypalUri(); 
$url = $url."?".$req;
$paypalreply = file_get_contents($url);
$paypalreply = trim($paypalreply);
if ($paypalreply == self::VALID) {
            return true;
        } else {
            return false;
        }
```
I had to "TRIM" Paypal answer because I receive VALID or INVALID followed by 100 space characters.
