### ISSUE TITLE
Feature request: recognize PayPal's fatal failures

### ISSUE THREAD

**Issue by willemstuursma** [mike182uk/paypal-ipn-listener#38]
We occasionally get these exceptions: 

```
Unexpected verification status encountered: <html>
<body>
Fatal Failure <br>
</body>
</html>
```

Apparently PayPal is sometimes experiencing a minor downtime. It would be great, if the library could recognize these errors and have map them to  a `\Mdb\PayPal\Ipn\Event\MessageVerificationFailureEvent`.

**Comment by mike182uk** [comment]
Hey @willemstuursma 

This is something that should already be happening unless I'am missing something?

https://github.com/mike182uk/paypal-ipn-listener/blob/3b3c99ad387349a64ae67db0a984ce5f7258f3bb/src/Listener.php#L51-L63

which is triggered by

https://github.com/mike182uk/paypal-ipn-listener/blob/3b3c99ad387349a64ae67db0a984ce5f7258f3bb/src/Verifier.php#L36-L40

**Comment by willemstuursma** [comment]
@mike182uk yes, you are right. I guess it would be nice to have a dedicated event, but on second thoughts its also not super useful because the `IPN_VERIFICATION_FAILURE_EVENT` already exist.
