### ISSUE TITLE
Add guzzlehttp/guzzle  7 support

### ISSUE THREAD

**Issue by garyross** [mike182uk/paypal-ipn-listener#42]
[Editted]
At the moment, there is no `guzzlehttp/guzzle` 7 support for v9.0.0 but there is for dev-master 

`- mike182uk/paypal-ipn-listener v9.0.0 requires guzzlehttp/guzzle ^6.2 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].`

Laravel 8 for example requires Guzzle 7.
Thanks!

**Comment by garyross** [comment]
Um, I see that your composer does indeed have guzzle7 support. Sorry about that. I wonder why I'm having issues here.

**Comment by garyross** [comment]
I see. The support is only for the `dev-master`, but not for version 9.0.0. I wonder if you could create a v9.0.1 with the support.

**Comment by mike182uk** [comment]
Hey @garyross 

I've published `9.0.1` with the changes from master 👍
