### ISSUE TITLE
PHP8 deprecation Exception for http_build_query

### ISSUE THREAD

**Issue by garyross** [mike182uk/paypal-ipn-listener#46]
Exception Message in PHP8.1:
`http_build_query(): Passing null to parameter #2 ($numeric_prefix) of type string is deprecated in mike182uk/paypal-ipn-listener/src/Message.php on line 42`

currently:
```
public function __toString() : string
    {
        return http_build_query($this->getAll(), null, '&');
    }

```
fix:
```
public function __toString() : string
    {
        return http_build_query($this->getAll(), '', '&');
    }
```

**Comment by mike182uk** [comment]
Thanks for the PR to resolve this @garyross 

Have merged it in and released the changes in `9.0.3` 👍
